[build.environment]
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/slides/0330-ext-vue/*"
  to = "/slides/0330-ext-vue/index.html"
  status = 200

[[redirects]]
  from = "/slides/1025-vue-tw-slidev/*"
  to = "/slides/1025-vue-tw-slidev/index.html"
  status = 200
